name: tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 2 * * *'

env:
  PHP_CS_FIXER_IGNORE_ENV: 1

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      max-parallel: 15
      matrix:
        os: [ ubuntu-latest ]
        php: [ "8.3", "8.2", "8.1", "8.0" ]
    name: PHP ${{ matrix.php }} Test on ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install PHP
        uses: shivammathur/setup-php@master

        with:
          php-version: ${{ matrix.php }}
          extension-csv: mbstring, xdebug
          ini-values-csv: "post_max_size=256M, short_open_tag=On"
          coverage: xdebug

      - name: Check PHP Version
        run: php -v

      - name: Check Composer Version
        run: composer -V

      - name: Check PHP Extensions
        run: php -m

      - name: Install Dependencies
        run: composer install

      - name: Run Analyse
        run: composer analyse src

      - name: Run Test
        run: composer test
